baseURL: https://blog.jordansimonov.ski/
title: Jordan Simonovski
Copyright: Jordan Simonovski
googleAnalytics: UA-134665544-1
disqusShortname: jordansimonovski

baseurl: '/'
languageCode: en-us"
theme: terminal
paginate: 5

params:
  contentTypeName: posts
  themeColor: green
  showMenuItems: 2
  description: 'Rants. Opinions. TILs.'
  images:
    - https://i.imgur.com/zL82z40.png
  twitterLink: https://twitter.com/_jsimonovski
  githubLink: https://github.com/jordan-simonovski

languages:
  en-us:
    title: Jordan Simonovski
    subtitle: Rants | TILs | Opinions
    keywords: ''
    copyright: Jordan Simonovski
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
  en:
    params:
      logo:
        logoText: Jordan Simonovski
        logoHomeLink: /
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts