description = "How introducing DevOps and SRE within the constraints of your organisation can help you win battles in your fight for better IT Operations."
images = ["https://cdn-images-1.medium.com/max/1600/1*XssIvsJiNPGxxeorIzpYPw.gif"]
title = "DevOps & Enterprise — Introducing Cultural Change to Big Organisations"