description = "Determining the teams you need to work with, understanding your constraints, and building something to try and solve the operational issues of an organisation."
images = ["https://cdn-images-1.medium.com/max/1600/1*XxOLwjH2eu13sATwysIqsA.gif"]
title = "DevOps & Enterprise — Part Deux"