description = "How my move out of a product team to an infrastructure team, and back again changed my view on DevOps and end-to-end ownership of products."
images = ["https://cdn-images-1.medium.com/max/1600/1*TMOPe9-PGh6D36cBBd0DPw.gif"]
title = "There and Back Again"